package npcgen

//NPC is the overall container for a non-player character generated by npcgen package
type NPC struct {
	HitPoints     DiceFunction
	BaseStatBlock StatBlock

	Race NPCRace
}

//ACMod is for modif
type ACMod struct {
	Set      int //Sets base AC of character to this value
	Addition int //Adds this to character's AC no questions asked

	AddMaxAbilityScores AbilityScores //Allows up to this much of each abilityScore to be added to the character's AC, -1 for infinite
}

//AbilityScores are used to hold the default six scores
type AbilityScores struct {
	Str AbilityScore
	Dex AbilityScore
	Con AbilityScore
	Int AbilityScore
	Wis AbilityScore
	Cha AbilityScore
}

//AbilityScore is a handy type which allows us to easily compute modifier values
type AbilityScore int

//Modifier allows us to compute the modifier value on a AbilityScore
func (a AbilityScore) Modifier() int {
	return 0
}

//StatBlock is to be used on items, NPCs, races etc to enable calculation of NPC / PC final stats
type StatBlock struct {
	AbilityScores

	TempHP int
	Size   int
	Speed  int

	ACMod
}

//CombineStatBlocks combines two statblocks together
func CombineStatBlocks(a, b StatBlock) StatBlock {
	return StatBlock{} //TODO
}

//AC returns the final AC of the character
func (n NPC) AC() int {
	return 10 //TODO
}

//HP returns the final max hitpoints of the character
func (n NPC) HP() int {
	return n.HitPoints.Evaluate() + len(n.HitPoints.Dice)*n.StatBlock().Con.Modifier() //TODO: make more efficient by caching n.StatBlock()?
}

//StatBlock returns the final statblock of the character (combining all other statblocks)
func (n NPC) StatBlock() StatBlock {
	return StatBlock{} //TODO
}

//GetAllActions returns all Actions that a NPC can do
func (n NPC) GetAllActions() []Action {
	return nil //TODO
}

//GetAllReactions returns all Actions that a NPC can do
func (n NPC) GetAllReactions() []Action {
	return nil //TODO
}

//GetAllFeatures returns all Features that a NPC can do
func (n NPC) GetAllFeatures() []Feature {
	return nil //TODO
}

var BanditCaptain = NPC{
	BaseStatBlock: StatBlock{
		AbilityScores: AbilityScores{
			Str: 15,
			Dex: 16,
			Con: 14,
			Int: 14,
			Wis: 11,
			Cha: 14,
		},
	},
	HitPoints: DiceFunction{
		Dice:     RepeatDie(DieTypeD8, 10),
		Constant: 0,
	},
}
